version: '3'
services:
  frontend:
    command: bash -c 'npm i && npm run dev'
    build:
      context: .
    expose:
      - '2000'
    image: node
    ports:
      - '2000:2000'
    user: node:16
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app