import Head from 'next/head'
import DefaultLayout from "../../layouts/DefaultLayout";
import Link from 'next/link'
import WorkCard from "../../components/cards/WorkCard";

const WorksPage = ({works}) => {

    console.log({works})
  return (
      <DefaultLayout>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className="container works">
              <ul className="works-container">
                  {works.map((work, index) => (
                      <li key={index}>
                          <WorkCard work={work}/>
                      </li>
                  ))}
              </ul>
          </main>

      </DefaultLayout>
  )
}

export async function getStaticProps() {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/works`)
    const works = await res.json()
    return {
        props: {
            works,
        }
    }
}

export default WorksPage
