import Head from 'next/head'
import DefaultLayout from "../../layouts/DefaultLayout";
import WorkCard from "../../components/cards/WorkCard";
import useSWR from "swr";

const fetcher = (...args) => fetch(...args).then((res) => res.json())

const WorksPage = ({works}) => {

    const { data, error } = useSWR('/api/works', fetcher)

    if(!data) return null;

  return (
      <DefaultLayout>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className="container works">
              <h1 className="section-title">Works</h1>
              <ul className="works-container">
                  {data.map((work, index) => (
                      <li key={index}>
                          <WorkCard work={work}/>
                      </li>
                  ))}
              </ul>
          </main>

      </DefaultLayout>
  )
}

export default WorksPage
