import Head from 'next/head'
import DefaultLayout from "../../layouts/DefaultLayout";
import Link from 'next/link'
import fs from 'fs'
import path from "path"

const WorksPage = ({works}) => {

  return (
      <DefaultLayout>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className="works">
              {works.map((work, index) => (
                  <li key={index}>
                      <Link href={`/works/${work.slug}`}>
                          {work.slug}
                      </Link>
                  </li>
              ))}
          </main>

      </DefaultLayout>
  )
}

export async function getStaticProps() {
    const files = fs.readdirSync(path.join('./datas/works'))
    const works = files.map((filename) => {
        const slug = filename.replace('.md', '')
        return {
            slug
        }
    })

    return {
        props: {
            works,
        }
    }
}

export default WorksPage
