import Head from 'next/head'
import DefaultLayout from "../layouts/DefaultLayout";
import IntroductionSection from "../components/homepage/IntroductionSection";
import SkillsSection from "../components/homepage/SkillsSection";
import AboutSection from "../components/homepage/AboutSection";
import RandomQuote from "../components/footer/RandomQuote";

const Home = () => {
  return (
      <DefaultLayout>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className="homepage">
              <IntroductionSection/>

              <SkillsSection/>

              <AboutSection/>

              <div className="section container">
                  <div className="card">
                      <RandomQuote/>
                  </div>
              </div>
          </main>

      </DefaultLayout>
  )
}

export default Home
