import Head from 'next/head'
import styles from '../styles/layouts/Home.module.css'
import DefaultLayout from "../layouts/DefaultLayout";
import IntroductionSection from "../components/homepage/IntroductionSection";

const Home = () => {
  return (
      <DefaultLayout>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>

              <IntroductionSection/>

              <section className={styles.techoAndTools}>
                  <div className={"container"}>
                      <h2>Technologies & Tools I work with</h2>
                      <div className={styles.grid2}>

                      </div>
                  </div>
              </section>

              <section className={styles.about}>
                  <div className={"container"}>
                      <h2>About me</h2>

                  </div>
              </section>

          </main>

      </DefaultLayout>
  )
}

export default Home
